apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grok2api-node-data
  labels:
    app.kubernetes.io/name: grok2api
    app.kubernetes.io/component: node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
